name: 'Build deploy'
description: 'Builds containers, pushes them to docker repo, deploys on k8s cluster'
runs:
  using: "composite"
  steps:
    - name: "Make kube directory"
      shell: bash
      run: mkdir ~/.kube
    - name: "Setup kubectl config for auth"
      shell: bash
      run: echo $KUBECTL_CONFIG_BASE64 | base64 --decode > ~/.kube/config
    - name: "Setup helm secret."
      shell: bash
      run: echo "$HELM_SECRET_BASE64" | base64 --decode > $SECRET_FILE
    - name: "Ozone - Build deploy test."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone r -c static-ns-k8s -d all-test