name: 'Delete namespace'
description: 'Deletes namespace, thereby destroying the PR sandbox'
inputs:
  k8s_config_base64:
    description: 'Base64 encryption of k8s config'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Make kube directory"
      shell: bash
      run: mkdir ~/.kube;
    - name: "Setup kubectl config for auth"
      shell: bash
      run: echo $KUBECTL_CONFIG_BASE64 | base64 --decode > ~/.kube/config
    - name: Install deps
      uses: ./.github/actions/install-deps
    - name: "Teardown namespace."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone r -c dynamic-ns-k8s -d delete-namespace
      env:
        GIT_BRANCH: ${{ github.head_ref }}