---
apiVersion: v1
kind: Secret
metadata:
  name: ozone
type: Opaque
stringData:
  MICRO_A_HOST: "micro-a"
  MICRO_B_HOST: "micro-b"
  HEALTH_CHECKER_PORT: "8080"
  MICRO_A_PORT: "8081"
  MICRO_B_PORT: "8082"