name: 'Run postman health tests'
runs:
  using: "composite"
  steps:
    - name: "Ozone - Build deploy."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone r -c $CONTEXT -d postman-health-check