name: 'Build deploy'
description: 'Builds containers, pushes them to docker repo, deploys on k8s cluster'
runs:
  using: "composite"
  steps:
    - name: "Make kube directory"
      shell: bash
      run: mkdir ~/.kube
    - name: "Setup kubectl config for auth"
      shell: bash
      run: echo $KUBECTL_CONFIG_BASE64 | base64 --decode > ~/.kube/config
    - name: "Login with docker hub."
      shell: bash
      run: echo "$DOCKERHUB_USERNAME" | docker login $DOCKER_REGISTRY -u "$DOCKERHUB_USERNAME" --password-stdin
    - name: "Apply image pull secret"
      shell: bash
      run: ./projects/script-common/applyImagePullSecret.sh $SUBDOMAIN
    - name: "Change ws-data-persistence to branch."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ./script/changeDataPersistenceBranch.sh
    - name: "Build branch and deploy."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ./script/buildWebshrinkerWithNamespace.sh $DOMAIN $SUBDOMAIN
    - name: "Sleep 150s to allow containers to start etc..."
      shell: bash
      run: sleep 150
