name: Merge/Push to a base branch (develop/epics)
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install deps
        uses: ./.github/actions/install-deps
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14
      - name: Build deploy
        uses: ./.github/actions/build-and-deploy
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: Run health check
        uses: ./.github/actions/postman-health-test
        env:
          SUBDOMAIN: ${{ steps.get_subdomain.outputs.url_safe }}
      - name: Run postman tests
        uses: ./.github/actions/postman-e2e-test
        env:
          SUBDOMAIN: ${{ steps.get_subdomain.outputs.url_safe }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      KUBECTL_CONFIG_BASE64: ${{ secrets.KUBECTL_CONFIG_BASE64 }}
      HELM_SECRET_BASE64: ${{ secrets.HELM_SECRET_BASE64 }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKERHUB_USER: ozone2021
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      SECRET_FILE: "/home/runner/secret.yml"
      DOMAIN: "test.com"