name: Pull Request Opened / Committed to
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # token: ${{ secrets.GH_PAT }} # token not needed for opensource repos.
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Branch head_ref
        shell: bash
        run: echo ${{ github.head_ref }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ozone2021
          password: ${{ env.DOCKER_PASS }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14
      - name: Build deploy test
        uses: ./.github/actions/build-deploy
        with:
          docker_registry: ozone2021
          domain: oz0n3.com
          k8s_secret_base64: ${{ secrets.SECRET_BASE64 }}
          k8s_config_base64: ${{ secrets.KUBECTL_CONFIG_BASE64 }}
          git_branch: ${{ steps.extract_branch.outputs.branch }}
          context: ${{ env.CONTEXT }}
      - name: Test
        uses: ./.github/actions/postman-health-test
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          CONTEXT: ${{ env.CONTEXT }}
    env:
      CONTEXT: dynamic-ns-k8s
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}