name: Pull Request Closed/Merged
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types: [closed]

jobs:
  merge_pr:
    name: Pull request merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # token: ${{ secrets.GH_PAT }} # token not needed for opensource repos
      - name: "Make kube directory"
        shell: bash
        run: mkdir ~/.kube;
      - name: "Setup kubectl config for auth"
        shell: bash
        run: echo $KUBECTL_CONFIG_BASE64 | base64 --decode > ~/.kube/config
    env:
      KUBECTL_CONFIG_BASE64: ${{ secrets.KUBECTL_CONFIG_BASE64 }}
  close_pr_without_merge:
    name: Pull request closed without merge
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Make kube directory"
        shell: bash
        run: mkdir ~/.kube;
      - name: "Setup kubectl config for auth"
        shell: bash
        run: echo $KUBECTL_CONFIG_BASE64 | base64 --decode > ~/.kube/config
      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14
      - name: Install deps
        uses: ./.github/actions/install-deps
      - name: "Teardown namespace."
        run: cd $GITHUB_WORKSPACE && ozone r -c dynamic-ns-k8s -d delete-namespace
        env:
          GIT_BRANCH: ${{ github.head_ref }}
    env:
      KUBECTL_CONFIG_BASE64: ${{ secrets.KUBECTL_CONFIG_BASE64_STAGING }}