name: Pull Request Opened / Committed to
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # token: ${{ secrets.GH_PAT }} # token not needed for opensource repos
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build deploy test
        uses: ./.github/actions/build-deploy
        with:
          docker_user: ozone2021
          docker_pass: ${{ secrets.DOCKER_PASS }}
          docker_registry: docker.io
          domain: test.com
          k8s_secret_base64: ${{ secrets.SECRET_BASE64 }}
          git_branch: ${{ steps.extract_branch.outputs.branch }}
          context: ${{ env.CONTEXT }}
      - name: Test
        uses: ./.github/actions/build-deploy
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          CONTEXT: ${{ env.CONTEXT }}
    env:
      CONTEXT: dynamic-ns-k8s