name: Pull Request Opened / Committed to
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install deps
        uses: ./.github/actions/install-deps
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.$DOCKERHUB_USERNAME }}
          password: ${{ secrets.$DOCKERHUB_PASS }}
      - name: Build deploy test
        uses: ./.github/actions/build-and-deploy
      #- name: Run postman e2e tests
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      KUBECTL_CONFIG_BASE64: ${{ secrets.KUBECTL_CONFIG_BASE64 }}
      HELM_SECRET_BASE64: ${{ secrets.SECRET_BASE64_DEV }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      SECRET_FILE: "/home/runner/secret.yml"
      DOMAIN: "test.com"
